### ISSUE TITLE
Add Hotfix CI Branches

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2411]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Add specific branches (`release/*`) in addition to devel in CI.  This allows us to create hotfixs that don't merge with devel before they are released.

**Comment by LeStarch** [comment]
To exclude `release/documentation` we probably should follow the pattern: `release/v*.*.*-hotfix` instead

**Comment by thomas-bc** [comment]
It should be doable to do something like this
```
on:
  push:
    branches: [ devel , release/* ]
    branches-ignore: [ release/documentation ]
```

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches-and-tags
