### ISSUE TITLE
Add A CITATION.cff File For Citing This Project

### ISSUE THREAD

**Issue by astroesteban** [nasa/fprime#946]
| | |
|:---|:---|
|**_F´ Version_**|devel |
|**_Affected Component_**| None |
---
## Feature Description

GitHub recently announced [support for citations](https://github.blog/2021-08-19-enhanced-support-citations-github/) using  `ruby-cff`. In order to add a citation for F' we just need to create a `CITATION.cff` file.

I have a basic one I can add:
```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
title: "F': A Flight-Proven, Multi-Platform, Open-Source Flight Software Framework"
url: "https://github.com/nasa/fprime"
```

but I've left the authors blank. We could add the authors listed [on this paper](https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=4140&context=smallsat).

## Rationale

We make it easier for users to cite F' thus bolstering the recognition of the project and boosting the reference count on sites like Google Scholar. This could have potential benefit when making a business case for F', recognizes the work made by contributors, and making it easier for people to reference the project is just nice.
